const store=window.MeridianStore, esc=store.escape, money=store.money;
let state=store.load(),mode='demo',csrf='';
async function api(path,method='GET',data){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(data?{body:JSON.stringify(data)}:{})});let b;try{b=await r.json();}catch{throw Error('Live workspace needs the Node server. Follow the setup instructions in README.md.');}if(!r.ok){if(r.status===401&&mode==='live')lockLive();throw Error(b.error||'Request failed.');}return b;}
function lockLive(){csrf='';mode='locked';document.querySelector('main').hidden=true;$('logout').hidden=true;$('workspace-label').textContent='Live workspace · Owner sign-in required.';}
function setMode(next){mode=next;document.querySelector('main').hidden=false;$('logout').hidden=mode!=='live';$('workspace-label').textContent=mode==='live'?'Live workspace · Real orders and shared store data.':'Demo workspace · Sample orders and changes saved in this browser.';$('mode-help').textContent=mode==='live'?'Owner signed in. Live changes affect the shared storefront.':'Demo data stays separate from real orders.';document.querySelector('header>a').href=mode==='demo'?'index.html?demo=1':'index.html';render();}
const $=id=>document.getElementById(id);
function notify(text,error=false){$('notice').textContent=text;$('notice').style.borderColor=error?'#a02222':'#46652e';}
async function commit(next){if(mode==='live')state=await api('/api/state','PUT',next);else{store.save(next);state=next;}render();notify(mode==='live'?'Changes saved to the live store.':'Demo changes saved in this browser.');}
function orderTable(orders){return orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th><th>Details</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${esc(o.date)}</td><td>${money(store.orderTotal(o))}</td><td><span class="status">${esc(o.status)}</span></td><td><button data-order="${esc(o.id)}">View order</button></td></tr>`).join('')}</tbody></table>`:'<p>No orders match your search.</p>';}
function renderOrders(){const q=$('order-search').value.trim().toLowerCase(),status=$('order-filter').value;$('order-list').innerHTML=orderTable(state.orders.filter(o=>(!status||o.status===status)&&`${o.id} ${o.customer} ${o.email}`.toLowerCase().includes(q)));}
function render(){document.querySelector('.brand').textContent=state.settings.name.toUpperCase();document.title=`Store management | ${state.settings.name}`;
  const nonCancelled=state.orders.filter(o=>o.status!=='Cancelled');
  const metrics=[[mode==='live'?'Order value':'Sample order value',money(nonCancelled.reduce((n,o)=>n+store.orderTotal(o),0))],[mode==='live'?'Orders':'Sample orders',state.orders.length],['Awaiting dispatch',state.orders.filter(o=>o.status==='Processing').length],['Visible products',state.products.filter(p=>p.active).length]];
  $('metrics').innerHTML=metrics.map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`).join('');
  $('recent-orders').innerHTML=orderTable(state.orders.slice(0,5));renderOrders();
  const low=state.products.filter(p=>p.stock<=5);$('low-stock').innerHTML=low.length?low.map(p=>`<div class="stock-row"><span>${esc(p.name)}</span><span>${p.stock} remaining</span></div>`).join(''):'<p>All products have more than five units in stock.</p>';
  $('product-list').innerHTML=state.products.map(p=>`<article class="product"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div><h2>${esc(p.name)}</h2><p>${money(p.price)} · ${p.stock} in stock · ${p.active?'Visible':'Hidden'}</p></div><button data-product="${esc(p.id)}">Edit product</button></article>`).join('');
  const f=$('settings-form');f.elements.name.value=state.settings.name;f.elements.announcement.value=state.settings.announcement;
}
function editProduct(id){const p=id?state.products.find(p=>p.id===id):{id:'',name:'',style:'',price:0,stock:0,image:'',description:'',badge:'',active:true};if(!p)return;const f=$('product-form');for(const k of ['id','name','style','price','stock','image','description','badge'])f.elements[k].value=p[k];f.elements.active.checked=p.active;$('product-dialog-title').textContent=id?'Edit product':'Add product';$('product-error').textContent='';$('product-dialog').showModal();}
function viewOrder(id){const o=state.orders.find(o=>o.id===id);if(!o)return;const f=$('order-form');f.elements.id.value=id;f.elements.status.value=o.status;f.elements.paymentStatus.value=o.paymentStatus||'Unpaid';f.elements.notes.value=o.notes;$('order-dialog-title').textContent=o.id;$('order-error').textContent='';$('order-details').innerHTML=`<p>${esc(o.customer)}<br>${esc(o.email)}<br>${esc(o.date)}<br>Payment: ${esc(o.paymentStatus||'Sample')}</p>${o.items.map(i=>`<p>${esc(i.name)} × ${i.quantity} — ${money(i.unitPrice*i.quantity)}</p>`).join('')}<p><strong>Total: ${money(store.orderTotal(o))}</strong></p><p class="muted">Original order prices stay unchanged when you edit product prices.</p>`;$('order-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==b.dataset.view;for(const n of document.querySelectorAll('nav button'))n.removeAttribute('aria-current');b.setAttribute('aria-current','page');$('notice').textContent='';}if(b.dataset.product)editProduct(b.dataset.product);if(b.dataset.order)viewOrder(b.dataset.order);if(b.dataset.close)$(b.dataset.close).close();});
$('new-product').addEventListener('click',()=>editProduct());$('order-search').addEventListener('input',renderOrders);$('order-filter').addEventListener('change',renderOrders);
$('product-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const next=JSON.parse(JSON.stringify(state));const id=f.elements.id.value||`watch-${crypto.randomUUID()}`;const p={id,name:f.elements.name.value.trim(),style:f.elements.style.value.trim(),price:Number(f.elements.price.value),stock:Number(f.elements.stock.value),image:f.elements.image.value.trim(),description:f.elements.description.value.trim(),badge:f.elements.badge.value.trim(),active:f.elements.active.checked};const index=next.products.findIndex(p=>p.id===id);if(index<0)next.products.push(p);else next.products[index]=p;try{await commit(next);$('product-dialog').close();}catch(err){$('product-error').textContent=err.message;}});
$('order-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,next=JSON.parse(JSON.stringify(state)),o=next.orders.find(o=>o.id===f.elements.id.value);if(!o){$('order-error').textContent='This order no longer exists.';return;}o.status=f.elements.status.value;o.paymentStatus=f.elements.paymentStatus.value;o.notes=f.elements.notes.value;try{await commit(next);$('order-dialog').close();}catch(err){$('order-error').textContent=err.message;}});
$('settings-form').addEventListener('submit',async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const next=JSON.parse(JSON.stringify(state));next.settings={name:e.currentTarget.elements.name.value.trim(),announcement:e.currentTarget.elements.announcement.value.trim()};try{await commit(next);}catch(err){notify(err.message,true);}});
window.addEventListener('storage',e=>{if(mode==='demo'&&e.key===store.key){state=store.load();render();notify('Updated from another tab in this browser.');}});
render();

$('demo-mode').addEventListener('click',()=>{state=store.load();setMode('demo');notify('Demo workspace selected.');});
$('live-mode').addEventListener('click',async()=>{try{const config=await api('/api/config');if(!config.live)throw Error('Live workspace is unavailable.');const r=await api('/api/session');csrf=r.csrf;state=r.state;setMode('live');}catch(err){if(err.message==='Owner sign-in required.'){lockLive();$('login-error').textContent='';$('login-dialog').showModal();}else notify(err.message,true);}});
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const r=await api('/api/login','POST',{password:f.elements.password.value});csrf=r.csrf;state=r.state;f.reset();$('login-dialog').close();setMode('live');notify('Signed in to the live store.');}catch(err){$('login-error').textContent=err.message;}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout','POST',{});csrf='';state=store.load();setMode('demo');notify('Signed out. Demo workspace selected.');}catch(err){notify(err.message,true);}});
$('add-order').addEventListener('click',()=>{const f=$('new-order-form');f.reset();f.elements.productId.innerHTML=state.products.filter(p=>p.active&&p.stock>0).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ${money(p.price)} (${p.stock} in stock)</option>`).join('');$('new-order-mode').textContent=mode==='live'?'This creates a real order and reduces live stock.':'This creates a sample order in this browser only. Do not enter real customer details in demo mode.';$('new-order-error').textContent='';$('new-order-dialog').showModal();});
$('new-order-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const b={customer:f.elements.customer.value.trim(),email:f.elements.email.value.trim(),paymentStatus:f.elements.paymentStatus.value,items:[{productId:f.elements.productId.value,quantity:Number(f.elements.quantity.value)}],revision:state.revision};try{if(mode==='live'){const r=await api('/api/orders','POST',b);state=r.state;render();}else{const next=JSON.parse(JSON.stringify(state)),p=next.products.find(p=>p.id===b.items[0].productId),q=b.items[0].quantity;if(!p||!p.active||!Number.isSafeInteger(q)||q<1||q>p.stock)throw Error('Insufficient stock for this order.');p.stock-=q;next.orders.unshift({id:'DEMO-'+crypto.randomUUID(),date:new Date().toISOString().slice(0,10),customer:b.customer,email:b.email,paymentStatus:b.paymentStatus,status:'Processing',notes:'',items:[{productId:p.id,name:p.name,quantity:q,unitPrice:p.price}]});await commit(next);}$('new-order-dialog').close();notify(mode==='live'?'Real order created. Stock updated.':'Sample order created. Demo stock updated.');}catch(err){$('new-order-error').textContent=err.message;}});
setMode('demo');
