const store=window.MeridianStore, esc=store.escape, money=store.money;
let state=store.load();
const $=id=>document.getElementById(id);
function notify(text,error=false){$('notice').textContent=text;$('notice').style.borderColor=error?'#a02222':'#46652e';}
function commit(next){store.save(next);state=next;render();notify('Demo changes saved in this browser.');}
function orderTable(orders){return orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th><th>Details</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${esc(o.date)}</td><td>${money(store.orderTotal(o))}</td><td><span class="status">${esc(o.status)}</span></td><td><button data-order="${esc(o.id)}">View order</button></td></tr>`).join('')}</tbody></table>`:'<p>No orders match your search.</p>';}
function renderOrders(){const q=$('order-search').value.trim().toLowerCase(),status=$('order-filter').value;$('order-list').innerHTML=orderTable(state.orders.filter(o=>(!status||o.status===status)&&`${o.id} ${o.customer} ${o.email}`.toLowerCase().includes(q)));}
function render(){document.querySelector('.brand').textContent=state.settings.name.toUpperCase();document.title=`Store management | ${state.settings.name}`;
  const nonCancelled=state.orders.filter(o=>o.status!=='Cancelled');
  const metrics=[['Demo order value',money(nonCancelled.reduce((n,o)=>n+store.orderTotal(o),0))],['Demo orders',state.orders.length],['Awaiting dispatch',state.orders.filter(o=>o.status==='Processing').length],['Visible products',state.products.filter(p=>p.active).length]];
  $('metrics').innerHTML=metrics.map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`).join('');
  $('recent-orders').innerHTML=orderTable(state.orders.slice(0,5));renderOrders();
  const low=state.products.filter(p=>p.stock<=5);$('low-stock').innerHTML=low.length?low.map(p=>`<div class="stock-row"><span>${esc(p.name)}</span><span>${p.stock} remaining</span></div>`).join(''):'<p>All products have more than five units in stock.</p>';
  $('product-list').innerHTML=state.products.map(p=>`<article class="product"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div><h2>${esc(p.name)}</h2><p>${money(p.price)} · ${p.stock} in stock · ${p.active?'Visible':'Hidden'}</p></div><button data-product="${esc(p.id)}">Edit product</button></article>`).join('');
  const f=$('settings-form');f.elements.name.value=state.settings.name;f.elements.announcement.value=state.settings.announcement;
}
function editProduct(id){const p=id?state.products.find(p=>p.id===id):{id:'',name:'',style:'',price:0,stock:0,image:'',description:'',badge:'',active:true};if(!p)return;const f=$('product-form');for(const k of ['id','name','style','price','stock','image','description','badge'])f.elements[k].value=p[k];f.elements.active.checked=p.active;$('product-dialog-title').textContent=id?'Edit product':'Add product';$('product-error').textContent='';$('product-dialog').showModal();}
function viewOrder(id){const o=state.orders.find(o=>o.id===id);if(!o)return;const f=$('order-form');f.elements.id.value=id;f.elements.status.value=o.status;f.elements.paymentStatus.value=o.paymentStatus||'Unpaid';f.elements.notes.value=o.notes;$('order-dialog-title').textContent=o.id;$('order-error').textContent='';$('order-details').innerHTML=`<p>${esc(o.customer)}<br>${esc(o.email)}<br>${esc(o.date)}<br>Payment: ${esc(o.paymentStatus||'Sample')}<br>Source: ${esc(o.source||'Sample')}</p>${o.items.map(i=>`<p>${esc(i.name)} × ${i.quantity} — ${money(i.unitPrice*i.quantity)}</p>`).join('')}<p><strong>Total: ${money(store.orderTotal(o))}</strong></p><p class="muted">Original order prices stay unchanged when you edit product prices.</p>`;$('order-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==b.dataset.view;for(const n of document.querySelectorAll('nav button'))n.removeAttribute('aria-current');b.setAttribute('aria-current','page');$('notice').textContent='';}if(b.dataset.product)editProduct(b.dataset.product);if(b.dataset.order)viewOrder(b.dataset.order);if(b.dataset.close)$(b.dataset.close).close();});
$('new-product').addEventListener('click',()=>editProduct());$('order-search').addEventListener('input',renderOrders);$('order-filter').addEventListener('change',renderOrders);
$('product-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const next=store.load();const id=f.elements.id.value||`watch-${crypto.randomUUID()}`;const p={id,name:f.elements.name.value.trim(),style:f.elements.style.value.trim(),price:Number(f.elements.price.value),stock:Number(f.elements.stock.value),image:f.elements.image.value.trim(),description:f.elements.description.value.trim(),badge:f.elements.badge.value.trim(),active:f.elements.active.checked};const index=next.products.findIndex(p=>p.id===id);if(index<0)next.products.push(p);else next.products[index]=p;try{await commit(next);$('product-dialog').close();}catch(err){$('product-error').textContent=err.message;}});
$('order-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,next=store.load(),o=next.orders.find(o=>o.id===f.elements.id.value);if(!o){$('order-error').textContent='This order no longer exists.';return;}o.status=f.elements.status.value;o.paymentStatus=f.elements.paymentStatus.value;o.notes=f.elements.notes.value;try{await commit(next);$('order-dialog').close();}catch(err){$('order-error').textContent=err.message;}});
$('settings-form').addEventListener('submit',async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const next=store.load();next.settings={name:e.currentTarget.elements.name.value.trim(),announcement:e.currentTarget.elements.announcement.value.trim()};try{await commit(next);}catch(err){notify(err.message,true);}});
window.addEventListener('storage',e=>{if(e.key===store.key){state=store.load();render();notify('Updated from another tab in this browser.');}});
render();


$('add-order').addEventListener('click',()=>{state=store.load();const f=$('new-order-form');f.reset();f.elements.productId.innerHTML=state.products.filter(p=>p.active&&p.stock>0).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ${money(p.price)} (${p.stock} in stock)</option>`).join('');$('new-order-mode').textContent='This creates a demo order in this browser and reduces demo stock. Use fictional customer details.';$('new-order-error').textContent='';$('new-order-dialog').showModal();});
$('new-order-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;try{store.createOrder({customer:f.elements.customer.value,email:f.elements.email.value,paymentStatus:f.elements.paymentStatus.value,source:'Admin',items:[{productId:f.elements.productId.value,quantity:Number(f.elements.quantity.value)}]});state=store.load();render();$('new-order-dialog').close();notify('Demo order created. Stock updated.');}catch(err){$('new-order-error').textContent=err.message;}});
window.addEventListener('focus',()=>{state=store.load();render();});
window.addEventListener('meridian-store-change',()=>{state=store.load();render();});

const sessionKey='merlock-demo-owner';
function showDashboard(){let signedIn=false;try{signedIn=sessionStorage.getItem(sessionKey)==='signed-in';}catch{}$('dashboard').hidden=!signedIn;$('login-screen').hidden=signedIn;$('demo-logout').hidden=!signedIn;if(signedIn){state=store.load();render();}}
$('demo-login-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(f.elements.username.value.trim()!=='owner'||f.elements.password.value!=='MerlockDemo123!'){$('login-error').textContent='Incorrect demo username or password.';return;}try{sessionStorage.setItem(sessionKey,'signed-in');f.reset();$('login-error').textContent='';showDashboard();}catch{$('login-error').textContent='Enable session storage in your browser to use the demo login.';}});
$('demo-logout').addEventListener('click',()=>{try{sessionStorage.removeItem(sessionKey);}catch{}for(const d of document.querySelectorAll('dialog'))d.close();showDashboard();});
showDashboard();
