const store=window.MeridianStore,esc=store.escape,money=store.money,$=id=>document.getElementById(id);
let state=store.load();const bag=new Map();let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',2500);}
function render(){state=store.load();document.title=state.settings.name+' | Time, well chosen.';document.querySelectorAll('.logo').forEach(el=>el.textContent=state.settings.name.toUpperCase());document.querySelector('.announcement').textContent=state.settings.announcement;$('year').textContent=new Date().getFullYear();
  for(const [id,q]of bag){const p=state.products.find(p=>p.id===id);if(!p||!p.active||p.stock===0)bag.delete(id);else if(q>p.stock)bag.set(id,p.stock);}
  $('products').innerHTML=state.products.filter(p=>p.active).map(p=>`<article><div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.style)} watch" loading="lazy"><span class="badge">${esc(p.badge)}</span></div><div class="product-info"><div><h3>${esc(p.name)}</h3><p>${esc(p.style)}</p></div><span class="price">${money(p.price)}</span></div><div class="product-actions"><button data-details="${p.id}">View details</button><button data-add="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Out of stock':'Add to bag'}</button></div></article>`).join('')||'<p>No products are currently available.</p>';renderBag();
}
function bagItems(){return [...bag].map(([id,quantity])=>({product:state.products.find(p=>p.id===id),quantity}));}
function renderBag(){const items=bagItems();$('bag-count').textContent=items.reduce((s,i)=>s+i.quantity,0);$('cart-items').innerHTML=items.length?items.map(({product:p,quantity:q})=>`<div class="cart-row"><div><p>${esc(p.name)}</p><div class="quantity"><button data-quantity="${p.id}" data-delta="-1" aria-label="Decrease ${esc(p.name)} quantity">−</button><span>${q}</span><button data-quantity="${p.id}" data-delta="1" aria-label="Increase ${esc(p.name)} quantity" ${q>=p.stock?'disabled':''}>+</button><button class="remove" data-remove="${p.id}" style="width:auto">Remove</button></div></div><span>${money(p.price*q)}</span></div>`).join(''):'<p class="details">Your bag is empty. Find a watch that feels like you.</p>';$('subtotal').textContent=money(items.reduce((s,i)=>s+i.quantity*i.product.price,0));$('checkout-button').disabled=!items.length;if($('checkout-dialog').open)renderCheckout();}
function addToBag(id){state=store.load();const p=state.products.find(p=>p.id===id);if(!p||!p.active)throw Error('Unknown product');if((bag.get(id)||0)>=p.stock){toast('No more stock available');return {error:'Insufficient stock'};}bag.set(id,(bag.get(id)||0)+1);render();toast('Added to your bag');return {product:id,quantity:bag.get(id),totalItems:[...bag.values()].reduce((a,b)=>a+b,0)};}
function showDetails(id){state=store.load();const p=state.products.find(p=>p.id===id&&p.active);if(!p)return;const img=$('detail-img');img.src=p.image;img.alt=p.style+' watch';$('detail-title').textContent=p.name;$('detail-copy').textContent=p.description+' '+money(p.price);$('detail-add').disabled=p.stock===0;$('detail-add').textContent=p.stock===0?'Out of stock':'Add to bag';$('detail-add').onclick=()=>{addToBag(id);$('details-dialog').close();};$('details-dialog').showModal();}
function openBag(){render();$('bag-dialog').showModal();}
function renderCheckout(){const items=bagItems();$('checkout-summary').innerHTML=items.map(({product:p,quantity:q})=>`<p>${esc(p.name)} × ${q} — ${money(p.price*q)}</p>`).join('')+`<div class="total"><strong>Total</strong><strong>${money(items.reduce((s,i)=>s+i.quantity*i.product.price,0))}</strong></div>`;$('place-order').disabled=!bag.size;}
function startCheckout(){render();if(!bag.size)return;$('bag-dialog').close();$('checkout-error').textContent='';renderCheckout();$('checkout-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.details)showDetails(b.dataset.details);if(b.dataset.add)addToBag(b.dataset.add);if(b.dataset.remove){bag.delete(b.dataset.remove);renderBag();}if(b.dataset.quantity){state=store.load();const p=state.products.find(p=>p.id===b.dataset.quantity);if(!p)return;const q=(bag.get(p.id)||0)+Number(b.dataset.delta);if(q<=0)bag.delete(p.id);else bag.set(p.id,Math.min(q,p.stock));render();}});
$('checkout-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;$('place-order').disabled=true;try{const order=store.createOrder({customer:f.elements.customer.value,email:f.elements.email.value,paymentStatus:'Demo — no payment',source:'Storefront',items:[...bag].map(([productId,quantity])=>({productId,quantity}))});bag.clear();render();$('checkout-dialog').close();$('confirmation-text').textContent=order.id+' · '+money(store.orderTotal(order))+' — saved to the admin Orders page.';$('confirmation-dialog').showModal();}catch(err){$('checkout-error').textContent=err.message;$('place-order').disabled=!bag.size;}});
window.addEventListener('storage',e=>{if(e.key===store.key)render();});window.addEventListener('focus',render);window.addEventListener('meridian-store-change',render);
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_watch_to_bag',description:'Add one demo watch to the visible bag. Does not place an order.',inputSchema:{type:'object',properties:{productId:{type:'string'}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input.productId!=='string'||Object.keys(input).some(k=>k!=='productId'))throw Error('A valid productId is required');return addToBag(input.productId);}})).catch(()=>{});}catch{}}
render();
